### ISSUE TITLE
convertStdEigenVectorToLLB(point_cloud)

### ISSUE THREAD

**Issue by Whatguia** [athrva98/llb-features#6]
function error ，the example cannot run

**Comment by athrva98** [comment]
@Whatguia Will check this out, with the latest changes to the code, it is possible that the examples are broken.

**Comment by Whatguia** [comment]
when

**Comment by athrva98** [comment]
Should be addressed by #9 
Let me know if you issues are resolved.

**Comment by Xi-Hsu** [comment]
it's working thx   
by the way in llb_features.hpp   line 149 .‘ SearchParams’: is not a member of ‘nanoflann’ in t the new vision function SearchParams already became to SearchParameters，i'm use old vision .

**Comment by athrva98** [comment]
> by the way in llb_features.hpp line 149 .‘ SearchParams’: is not a member of ‘nanoflann’ in t the new vision function SearchParams already became to SearchParameters，i'm use old vision .

Yes, I need to update the nanoflann library, will do in a followup commit.
